apiVersion: v1
kind: Service
metadata:
  name: dsa-visualizer-service
spec:
  type: NodePort
  selector:
    app: dsa-visualizer
  ports:
    - protocol: TCP
      port: 6080
      targetPort: 6080
      nodePort: 30080
